### PR TITLE
Fix segfault, disable V8's thread-isolated allocator

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes: https://github.com/rubyjs/mini_racer/issues/300

### CODE REVIEW

**Comment by bnoordhuis** [comment]
This is against V8 12.x. Is there a specific branch I should be targeting instead of main? libv8-node-22?

**Comment by SamSaffron** [comment]
Sorry for the short reply, getting late :)

You will need to also edit version.rb to target the right version, we
reverted that when we were debugging the segfaults

Is this patch going to be easy to maintain?

**Comment by bnoordhuis** [comment]
I'll take a closer look tomorrow why `rake test` segfaults (it's not a pkey thing) but if it's not something straightforward, I'll just PR libv8-node instead and disable PKRU in V8.

**Comment by bnoordhuis** [comment]
I'll PR libv8-node instead, closing.

**Pull request closed without merging**
