### PR TITLE
Update to use libv8-node 16.x

### PR DESCRIPTION
**Pull request by lloeki**
Based on V8 9.0, with node 16 being the new LTS, node 15 now being unsupported. It
notably introduces single threaded mode.

Requiring c++14 is apparently the only change needed for this major. A
separate PR will add a more helpful install time check for compiler
requirements.

### CODE REVIEW

**Comment by lloeki** [comment]
Do not merge yet!

libv8-node 16 hasn't been released on ruby gems (hence the test failures), as I need to finalise the CI support for cross compiling to ARM before I have public things out there (even beta).

This early branch allows select testers to proceed with testing on private gems, as well as libv8-node CI's test jobs (which are based on mini_racer) to pass.

**Comment by lloeki** [comment]
Cross-compilation of Node 16 to aarch64-linux is [making good progress](https://github.com/sqreen/ruby-libv8-node/issues/8#issuecomment-878238712), so I should be publishing the gems when I get to fix a small (known) issue on musl.

@SamSaffron I have a couple of flaky test failures on x86_64-darwin CI. I think they might be due to the CI machines suffering from the occasional pressure, which makes stuff not happen in a timely manner from time to time. I'm not sure if there's a way to improve these:

```
Run options: --seed 6360

# Running:

...................S......S......................F........................................

Finished in 4.243624s, 21.2083 runs/s, 35.3471 assertions/s.

  1) Failure:
MiniRacerTest#test_ensure_gc [/Users/runner/work/ruby-libv8-node/ruby-libv8-node/test/mini_racer/test/mini_racer_test.rb:757]:
expecting most of the 1_000_000 long string to be freed

90 runs, 150 assertions, 1 failures, 0 errors, 2 skips
```

```
Run options: --seed 17030

# Running:

.........................F....S...............................................S...........

Finished in 4.744077s, 18.9710 runs/s, 31.6184 assertions/s.

  1) Failure:
MiniRacerTest#test_timeout_in_ruby_land [/Users/runner/work/ruby-libv8-node/ruby-libv8-node/test/mini_racer/test/mini_racer_test.rb:645]:
MiniRacer::ScriptTerminatedError expected but nothing was raised.

90 runs, 150 assertions, 1 failures, 0 errors, 2 skips
```

**Comment by lloeki** [comment]
Had to disable pointer compression (which is experimental) because of [this commit](https://github.com/v8/v8/commit/e28dadc2070b202aab77b9e50a46e50be02f8f1c).

**Comment by lloeki** [comment]
1. `x86_64` 2.6 gnu and 2.7 gnu failed because they picked up `x86_64-linux-musl` instead of `x86_64-linux`. Old rubygems issue, fixed upstream.
2. `x86_64` 2.6 musl and 2.7 musl failed because they think they're `x86_64-linux` and points the linker to a nonexistent file. Same old rubygems issue, but manifests differently. I might be able to work around that one within libv8-node.
3. `aarch64-linux-musl` libv8-node is unreleased (no cross-compiling for musl), so it picks up `aarch64-linux` and fails. I'll produce a build using Docker on my M1 machine.
4. `x86_64` 3.0 musl failed because of [this upstream ruby issue](https://bugs.ruby-lang.org/issues/17788) for which IIUC a fix has been merged but not released. IIRC using `clang` can work around that, or we can try applying the small patch on that Ruby.
5. Not sure what happened on macOS 11.0, it seems unrelated to `mini_racer`:

```
#<Thread:0x00007fcb8d0796e8 /Users/runner/work/mini_racer/mini_racer/test/mini_racer_test.rb:587 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:73:in `bytes': stack level too deep (SystemStackError)
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:260:in `gen_random'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:73:in `bytes'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:260:in `gen_random'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:73:in `bytes'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:260:in `gen_random'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:73:in `bytes'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:260:in `gen_random'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:73:in `bytes'
	 ... 10908 levels...
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:260:in `gen_random'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:155:in `random_bytes'
	from /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/securerandom.rb:176:in `hex'
	from /Users/runner/work/mini_racer/mini_racer/test/mini_racer_test.rb:588:in `block (2 levels) in test_concurrent_access_over_the_same_isolate_2'
```

**Comment by SamSaffron** [comment]
I am merging this, but will wait a bit till I push gems for a bit longer

**Comment by alexeevit** [comment]
@lloeki hey hi

> 1. x86_64 2.6 gnu and 2.7 gnu failed because they picked up x86_64-linux-musl instead of x86_64-linux. Old rubygems issue, fixed upstream.
> 2. x86_64 2.6 musl and 2.7 musl failed because they think they're x86_64-linux and points the linker to a nonexistent file. Same old rubygems issue, but manifests differently. I might be able to work around that one within libv8-node.

I'm not sure what's the difference between these points, but I ran into the issue on my x86_64 Linux VPS. It thinks it's `x86_64-linux` but it picked up `x86-64-linux-musl`. Is there a quick workaround to make it work?

**Comment by lloeki** [comment]
@alexeevit it's very subtle, see https://github.com/rubygems/rubygems/issues/3174 for gory details. The true fix is not there yet but are workarounds in latest rubygems and bundler, so what's your rubygems and bundler version?

**Comment by alexeevit** [comment]
> @alexeevit it's very subtle, see [rubygems/rubygems#3174](https://github.com/rubygems/rubygems/issues/3174) for gory details. The true fix is not there yet but are workarounds in latest rubygems and bundler, so what's your rubygems and bundler version?

```
$ gem -v
3.0.3.1
```

```
$ bundler -v
Bundler version 1.17.2
```

Then I'll try to update them first and come back with the result. Thank you!

**Pull request merged**
