### PR TITLE
Configurable max marshal stack depth

### PR DESCRIPTION
**Pull request by seanmakesgames**
builds on #201 (bit of a weird git history at the moment) -- will sort itself out with some squashing and merging other PRs.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Any chance you can measure the impact here? I am guessing it is negligible considering huge costs of cross vm serialization which would dwarf this. 

As long as you confirm this is totally negligible in the big scheme, perfectly happy to merge and not bother making this configurable.

Note there are going to still probably be hacks that can trigger explosions, like an object with 100k leaves each of which has another 100k leaves. Even at 5 deep people may be able to segfault? Do we just rely on memory limits for these cases?

**Comment by seanmakesgames** [comment]
For my use I would prefer a stack depth of 100 (mongodb max object size), and have it configureable.

Most of the resource-based DoSes have been mitigated by stuff that has already been done like memory caps. There are probably a few of these left, but much more edge-case-y.

I'm going to just add back in the configurability to this PR. It's a bit more code, but not that much. I'll also do a run of the benchmarking code if I can figure it out. Let me know if you have any comments about the implementation itself thus far.

**Comment by seanmakesgames** [comment]
You're right. Impact on perf with it on is noise:

With it set at 512:
```
Benching with mini_racer
-----on-------
mini_racer minify discourse_app.js 9613.315ms
-----on-------
mini_racer minify discourse_app_minified.js 8677.78ms
-----on-------
mini_racer minify discourse_app.js twice (2 threads) 10136.720000000001ms
```

With it switched off:
```
Benching with mini_racer
mini_racer minify discourse_app.js 9512.943ms
mini_racer minify discourse_app_minified.js 8620.75ms
mini_racer minify discourse_app.js twice (2 threads) 10319.359999999999ms
```

With the code commented out:
```
Benching with mini_racer
mini_racer minify discourse_app.js 9581.952ms
mini_racer minify discourse_app_minified.js 8766.073ms
mini_racer minify discourse_app.js twice (2 threads) 10500.054ms
```

**Comment by SamSaffron** [comment]
Oh I am not sure that is the right micro bench here :thinking: 

I would go for say something like this?  


```
1000.times do
   ctx.eval({a: {b: {c: "d"}}})
end
```

Can you rerun numbers? 

Happy for the default to be 1023.

**Comment by SamSaffron** [comment]
OK, since this is arguably measurable lets go with default off. 

Can you amend the PR to also explain about this knob in the README?

**Comment by seanmakesgames** [comment]
Readme updates should be in there. I'll update the default to off.

**Comment by seanmakesgames** [comment]
Default is off again. README was updated.

Did you want me to edit the PR description to talk more about the feature that was added here, or is the readme modification sufficient?

**Comment by SamSaffron** [comment]
I think this is good as is, will think over the next few days if it makes sense to have the safer default, given this will only impact outlier code.

**Pull request merged**
