### PR TITLE
WIP Mechanical compatibility changes

### PR DESCRIPTION
**Pull request by ignisf**

### CODE REVIEW

**Comment by SamSaffron** [comment]
Overall this looks fine to me, feel free to merge once ready.

**Comment by SamSaffron** [comment]
would love to get this merged sooner rather than later, do you think it is ready?

**Comment by nightpool** [comment]
Hey, any updates on this? There's a bug in v8 versions prior to 7.5.1 that make it impossible to use the snapshots feature with React DOM Server-side rendering. Would be really great if we could get this upgraded and fixed

**Comment by SamSaffron** [comment]
I would love love love to have support for latest v8. 

Heck Discourse would be happy to fund someone working on getting all of this upgraded.

**Comment by nightpool** [comment]
I took a shot at trying to get this to work myself, but I couldn't figure out how to get libv8 compiling from source as part of the bundle installation process. One error I ran into was unsynchronized chdir access:

```
Using libv8 7.8.279.0 from https://github.com/nightpool/libv8 (at v8-7.8@396315d)
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
```

Libv8 *looks* like it builds correctly, but when we get to compiling mini_racer, it can't find the libv8 gem:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
[...]
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in
`require': cannot load such file -- libv8 (LoadError)
from
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
	from extconf.rb:2:in `<main>'
```

I was able to get around this by using `-j1` as an option to `bundle install`, but then I ran into an ICU error when attempting to run Intl.DateFormat:

`#<MiniRacer::SnapshotError: TypeError: Internal error. Icu error.>`

Not really sure what this could mean, and i'm pretty stumped. Seems like it should be something simple in the build process, like a missing icu4 dependency at compile-time, but i'm having trouble getting bundler to even show libv8's log files half the time.

Compilation environment is a glibc, Debian Stretch docker container.

**Comment by nightpool** [comment]
I was also able to reproduce the ICU error with the beta version of libv8 published in December to rubygems: https://rubygems.org/gems/libv8/versions/7.8.279.23.0beta1-x86_64-linux

**Comment by nightpool** [comment]
I posted to v8-dev in the hopes that someone there might be able to point me in the right direction: https://groups.google.com/forum/?nomobile=true#!topic/v8-dev/y7BKAeAbYVM

**Comment by cataphract** [comment]
I gave it a go here against 8.4.307 here: https://github.com/sqreen/mini_racer/commit/f57ad9ac2110ff6285f7f7595764485ace40cf6c

and it works, except with one problem: I had to disable readonly heap on the v8 build (I didn't enable it on purpose but I disabled pointer compression and that enabled it automatically). I don't know if this worked before, but the snapshot/warmup tests lead to the assertion `CHECK_EQ(last_checksum, des->GetChecksum());` failing. I'm not sure what's going on there; it seems it expects all the isolates to have the same read-only heap but then the snapshot read only data is different... or something.

Commit is against our fork but should be easily cherry-pickable. This requires the libv8 gem to also be updated of course.

**Comment by SamSaffron** [comment]
Cool @cataphract can you do a PR to libv8. I think at this point I prefer disabling features and moving forward to stagnating. @ignisf are you around to do another libv8 release?

**Comment by nightpool** [comment]
@cataphract awesome! I'll try tomorrow to see if I can get my code running with that. 

might be useful to share that error message on the v8-dev thread I made, someone on there might have an idea what's going on: https://groups.google.com/forum/?nomobile=true#!topic/v8-dev/y7BKAeAbYVM

cc @bnoordhuis, who may also if there have been any changes to snapshots and warmup since 7.3

**Comment by bnoordhuis** [comment]
If you have an existing snapshot when creating the new one, pass it as the third argument to `SnapshotCreator`, that should ensure they use the same read-only heap.

If you don't pass it, it's going to use the default snapshot (if you use `V8::SetSnapshotBlob()` - but it looks like you don't) or no snapshot.

Compiling without RO heap is fine too. It's an optimization (less work for the GC) but not a critical one.

**Pull request closed without merging**
