### PR TITLE
Use libv8 node

### PR DESCRIPTION
**Pull request by lloeki**
This is a PR for people to try `mini_racer` using `libv8-node` built for Apple M1 or musl.

Note: this is only tested using a `rbenv install`'d Ruby (which builds as `arm64`), and untested using the system-provided Ruby (which is built as `arm64e`) as I have not yet found a way to build libv8/node as `arm64e`.

Since I don't fully consider `libv8-node` [ready for prime time yet](https://github.com/sqreen/ruby-libv8-node/issues), the original intent is not to merge this as is (if ever), but provide an easy testing ground via:

```ruby
# Gemfile
gem 'mini_racer', github: 'rubyjs/mini_racer', branch: 'refs/pull/186/head'
# or
gem 'mini_racer', github: 'sqreen/mini_racer', branch: 'use-libv8-node'
```

### CODE REVIEW

**Comment by sweetppro** [comment]
I get this error when running `bundle install` on my M1 MacBook Air...

`Could not find gem 'libv8-node (~> 15.5.1.0.beta1)', which is required by gem 'mini_racer', in any
of the sources.`

**Comment by lloeki** [comment]
@sweetppro Might be the same as this one: 

https://github.com/sqreen/ruby-libv8-node/issues/14#issuecomment-762945936

**Comment by SamSaffron** [comment]
@lloeki we now have 3 developers that had lots of luck with the the new gem. @davidtaylorhq was amongst them.

Performance on Discourse is pretty much spectacular on native M1. Looking forward to getting this new pattern into a production gem!

**Comment by sweetppro** [comment]
> @sweetppro Might be the same as this one:
> 
> [sqreen/ruby-libv8-node#14 (comment)](https://github.com/sqreen/ruby-libv8-node/issues/14#issuecomment-762945936)

Im getting this issue:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/me/myapp/gems/ruby/2.6.0/gems/sq_mini_racer-0.3.1.0.3/ext/mini_racer_extension
/Users/me/.rbenv/versions/2.6.5/bin/ruby -I /Users/me/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0 -r ./siteconf20210128-7070-s9t894.rb extconf.rb
  ERROR: found gems matching libv8-node:'~> 15.5.1.0.beta1', but no binary for -darwin-20
         try "gem install libv8-node:'~> 15.5.1.0.beta1'" to attempt to build libv8-node from source
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/me/.rbenv/versions/2.6.5/bin/$(RUBY_BASE_NAME)
platform ruby:-darwin20 rubygems:-darwin-20 detected:-darwin-20
looking for libv8-node-*--darwin-20 in ["/Users/me/myapp/gems/ruby/2.6.0"]
libv8-node-*--darwin-20 not found in ["/Users/me/myapp/gems/ruby/2.6.0"]
looking for libv8-node-*--darwin-20 in ["/Users/me/myapp/gems/ruby/2.6.0/gems/sq_mini_racer-0.3.1.0.3/ext/mini_racer_extension/vendor"]
libv8-node-*--darwin-20 not found in ["/Users/me/myapp/gems/ruby/2.6.0/gems/sq_mini_racer-0.3.1.0.3/ext/mini_racer_extension/vendor"]

extconf failed, exit code 1
```

**Comment by lloeki** [comment]
> I get this error when running bundle install on my M1 MacBook Air...

Sharing [this finding](https://github.com/sqreen/ruby-libv8-node/issues/14#issuecomment-768971366) here as well, one would really want to use Ruby >= 2.7.2 on M1, as versions before that are more or less subtly broken.

**Comment by 2called-chaos** [comment]
There is no way of utilizing Bundler's (2.2) enhanced platform support to auto-switch? I mean in the Gemfile directly, I guess using a local version via `bundler config local.mini_racer /some/path` is a way but requires some setup steps for M1 users.

**Comment by lloeki** [comment]
GitHub Actions results for 6b38556 [here](https://github.com/sqreen/mini_racer/actions/runs/722868071).

It fails on aarch64-linux (except on Ruby 3.0, go figure), might be because of the build on Apple Silicon (through a VM), might be because of QEMU, or an interaction between both. Travis seems to be fine with the build, although agonisingly slow to update rubygems. Ruby 3.0 aarch64-linux-musl fails but that might be because there's some specifics to that Docker image (I noticed the build env seems weirdly broken by default, e.g `CXX=''`)

**Comment by lloeki** [comment]
GitHub Actions results for 6b38556 [here](https://github.com/sqreen/mini_racer/actions/runs/722868071) and [here](https://github.com/sqreen/mini_racer/actions/runs/723286360).

It fails on aarch64-linux (except on Ruby 3.0, go figure), might be because of the build on Apple Silicon (through a VM), might be because of QEMU, or an interaction between both. Travis seems to be fine with the build, although agonisingly slow to update rubygems. Ruby 3.0 aarch64-linux-musl fails but that might be because there's some specifics to that Docker image (I noticed the build env seems weirdly broken by default, e.g `CXX=''`)

**Comment by SamSaffron** [comment]
Do you feel we are in a good enough state to start gathering public feedback by doing a pre-release gem of mini_racer?

**Comment by lloeki** [comment]
Yeah, I think it'll solve more issues than it "creates" (on platforms that weren't there before).

**Comment by lloeki** [comment]
BTW I think we can go straight to 0.4.0 (.beta1) given the change's magnitude.

**Comment by SamSaffron** [comment]
sure! sounds good to me!

**Comment by SamSaffron** [comment]
@lloeki I just pushed mini_racker 0.4.0.beta1 using node libv8!  :confetti_ball:  

Asking some colleagues with m1 macs to test it out! Seems to work fine on my Linux install.

**Comment by tisba** [comment]
Happy do run some tests on m1. Do you want to get feedback/issues here?

**Comment by sweetppro** [comment]
It seems to run just fine on my m1 MacBook Air.
Rails 6.1.3.1
Ruby 2.7.2p137
rbenv 1.1.2

**Comment by lloeki** [comment]
Thanks @SamSaffron!

@tisba positive reports should be OK here in this discussion, but please create a dedicated issue if there's a problem.

**Comment by jdelStrother** [comment]
seems good! At least from a casual test:

```ruby
irb(main):003:0> context = MiniRacer::Context.new
=> #<MiniRacer::Context:0x000000010f8faad8 @functions={}, @timeout=nil, @max_memory=nil, @current_exception=nil, @isolate=false, @ensure_gc_after_idle=nil, @disposed=false, @ca...
irb(main):004:0> context.eval 'var adder = (a,b)=>a+b;'
=> nil
irb(main):005:0> puts context.eval 'adder(20,22)'
42
=> nil
irb(main):006:0> RUBY_PLATFORM
=> "arm64-darwin20"
irb(main):007:0> RUBY_VERSION
=> "2.7.2"
irb(main):008:0> MiniRacer::VERSION
=> "0.4.0.beta1"
```

**Comment by SamSaffron** [comment]
@lloeki all our devs are having great success, should we go ahead and promote both v8 and mini_racer to release?

**Comment by tisba** [comment]
I have various crashes with the beta under M1 + Docker for Mac. I did not come around yet to compile details :(

**Comment by lloeki** [comment]
@tisba That's on aarch64-linux then? Please open a separate issue with the details.

Also can you try installing the `ruby` platform gem (which will take a while as it builds V8 upon install) and see if you have the same issues?

**Comment by lloeki** [comment]
Yup @SamSaffron let's do this. I'll push the updated `libv8-node` (there's node 15.14.0 out now) and then proceed with `mini_racer`.

**Comment by tisba** [comment]
Using a slight modified version of https://github.com/rubyjs/mini_racer/issues/170, using `rvm 2.7.2,2.7.3,3.0.0,3.0.1 do ruby ./mini_racer_hang.rb`, everything looks fine native on my Mac Mini M1.

**Comment by tisba** [comment]
Happy to report that the bigger test suite with a lot of mini_racer usage works fine natively on M1 using `0.4.0.beta1`! We kind of depend on also using it inside Docker which is not working yet (see #190) but the progress here makes me feel very optimistic. Thanks again for the work! 🙇

**Comment by bf4** [comment]
For me the upgrade (change from libv8 (~> 8.4.255) to  libv8-node (~> 15.14.0.0)) broke my usage of `String.prototype.localeCompare`. I probably need to make an issue in libv8-node but wanted to share here.

```ruby
function_body = <<~EOS
function localeCompare(a, b) {
  return (a || '').localeCompare((b || ''), 'en', { sensitivity: 'base' });
}
EOS

function = 'localeCompare'
inputs = [
  "Rich",
  "Rich"
]
expectation = true

snapshot = MiniRacer::Snapshot.new(function_body)
context = MiniRacer::Context.new(snapshot: snapshot)
result = context.call(function, *inputs) # throws RangeError: Internal error. Icu error.
expect(result).to eq(expectation) 
```

**Comment by SamSaffron** [comment]
@lloeki I guess we are missing ICU from the libv8 compile somehow? 

@bf4 can you test in node directly? does it work in node?

**Comment by lloeki** [comment]
It's a configure/build option. I remember dropping to small-icu but can't remember the reason (either size, or a failing build).

I'll try to do some builds with a bigger ICU.

**Comment by lloeki** [comment]
@bf4 Builds are out, a mini_racer install or pristine should do the work to build against the new one. 

We should probably keep further discussion on that at https://github.com/rubyjs/mini_racer/issues/196.

**Pull request merged**
